"""empty message

Revision ID: 2264c4ad35cc
Revises: f8ed803bed06
Create Date: 2022-08-17 21:21:08.364524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2264c4ad35cc'
down_revision = 'f8ed803bed06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('authenticated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authenticated', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
