"""empty message

Revision ID: 3146763e5af4
Revises: 512ea99d890c
Create Date: 2022-08-19 00:32:07.038689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3146763e5af4'
down_revision = '512ea99d890c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('test1', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('test1')
    )
    # ### end Alembic commands ###
