"""empty message

Revision ID: 512ea99d890c
Revises: 2264c4ad35cc
Create Date: 2022-08-18 17:42:50.910744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512ea99d890c'
down_revision = '2264c4ad35cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('exercise_plan_comment', schema=None) as batch_op:
        batch_op.drop_column('modify_date')

    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('meal_plan_comment', schema=None) as batch_op:
        batch_op.drop_column('modify_date')

    with op.batch_alter_table('study_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('study_plan_comment', schema=None) as batch_op:
        batch_op.drop_column('modify_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_plan_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('study_plan', schema=None) as batch_op:
        batch_op.drop_column('modify_date')

    with op.batch_alter_table('meal_plan_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.drop_column('modify_date')

    with op.batch_alter_table('exercise_plan_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('exercise_plan', schema=None) as batch_op:
        batch_op.drop_column('modify_date')

    # ### end Alembic commands ###
