"""empty message

Revision ID: 765a3305ecca
Revises: 9f6b749acdd7
Create Date: 2022-08-10 16:41:42.252852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765a3305ecca'
down_revision = '9f6b749acdd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_exercise_plan_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_plan'))
    )
    op.create_table('exercise_plan_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_plan_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_plan_id'], ['exercise_plan.id'], name=op.f('fk_exercise_plan_comment_exercise_plan_id_exercise_plan'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_exercise_plan_comment_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_plan_comment'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_plan_comment')
    op.drop_table('exercise_plan')
    # ### end Alembic commands ###
