"""empty message

Revision ID: 9f6b749acdd7
Revises: 8ee2ec8ace3d
Create Date: 2022-08-10 14:58:37.195074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6b749acdd7'
down_revision = '8ee2ec8ace3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_study_plan_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_plan'))
    )
    op.create_table('study_plan_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_plan_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['study_plan_id'], ['study_plan.id'], name=op.f('fk_study_plan_comment_study_plan_id_study_plan'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_study_plan_comment_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_plan_comment'))
    )
    op.drop_table('comment')
    op.drop_table('plan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=200), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_plan_user_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_plan')
    )
    op.create_table('comment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('plan_id', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('modify_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], name='fk_comment_plan_id_plan', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_comment_user_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_comment')
    )
    op.drop_table('study_plan_comment')
    op.drop_table('study_plan')
    # ### end Alembic commands ###
