"""empty message

Revision ID: f3684a32ea52
Revises: 351f195a59fc
Create Date: 2022-07-21 23:02:48.664964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3684a32ea52'
down_revision = '351f195a59fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('create_date', sa.DateTime(), nullable=False))
    op.drop_column('answer', 'create_data')
    op.add_column('question', sa.Column('create_date', sa.DateTime(), nullable=False))
    op.drop_column('question', 'create_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('create_data', sa.DATETIME(), nullable=False))
    op.drop_column('question', 'create_date')
    op.add_column('answer', sa.Column('create_data', sa.DATETIME(), nullable=False))
    op.drop_column('answer', 'create_date')
    # ### end Alembic commands ###
